# 异常和错误处理

只要是程序，就会有错误。程序越大，出现的错误也会越多。假如程序非常大的话.那么
我们想要彻底去掉所有的错误几乎是不可能的，我们的目标就是尽量地减少错误。

一般说来，**逻辑性**差的语句块会带来一些错误，程序只是按照编程者的思路去执行，假如编程者将算法写错.那么程序也会按照错误的算法执行，这自然会导致产生错误的结果:其次
是**语法问题**.比如用了错误的头文件、关键字.函数名或者类名等。这两种是最常见的，也是
编程人员经常检查并能够手动处理的错误。

另外一类错误不容易被发现，而且又很容易在运行时导致程序崩溃。比如说当程序要求你输入一个数字，你输入一个数字时运行得很好，但是当你输入一个字符时，程序就会崩溃:另外的情况则是当内存不足够程序使用，或者当硬盘某个扇区出现坏道导致程序不能写入数据。。。这类错误，我们称为**异常**。

- 常见的防御手段：

1. 当程序即将崩溃时，通知用户并安全退出。
2. 当程序即将崩溃时，通知并允许用户在保存数据后继续运行:假如崩溃已经发生.那么允许用户尽量恢复数据并继续执行，如word的文档恢复功能。
3. 当程序即将崩溃时，允许用户继续操作并限制用户使用可导致崩溃的操作。
4. 当程序即将崩溃时，什么都不做，任其崩溃。

C++为我们提供了可以解决在运行一个程序时出现的或者是可以预见的错误情况的集合
方法。

```c++
try
{
	wrong();//可能抛异常的方法
/*
大括号中是可能出问题的代码 
如果出问题 wrong会抛出异常
*/
}
catch(outofMemory/*错误类型*/)
{
    //处理错误
}
catch(FileNotFound)
{
    //可以多个catch块处理不同类型错误
}

```



```c++
#include <iostream>
using namespace std;
class wrong{};
void error()//
{
    cout<<"出错\n";
    throw wrong();//抛出一个异常，被后面catch捕获了
}
int main()
{
    try
    {
        error();//调用后会抛出异常
    }
    catch (wrong)
    {
        cout<<"该错误已经解决\n";
    }
    return  0;
}
```

```c++
#include <iostream>
using namespace std;
const int num=5;
class people
{
public:
    people(int size=num);
    people(const people&r);
    ~people(){delete[]p;}
    people&operator=(const people&);
    int&operator[](int off);
    const int&operator[](int off)const;
    int GetSize()const{return size;}
    friend ostream&operator<<(ostream&,const people&);
    class wrong{};
    //内部类,看着是空但是有默认构造，析构。。。
private:
    int *p;
    int size;
};
people::people(int Size):size(Size)
{
    p=new int[size];
    for (int i=0;i<size;i++)
    {
        p[i]=0;
    }
}
people&people::operator=(const people&r)
{
    if(this==&r)
    {
        return *this;
    }
    delete[]p;
    size=r.GetSize();
    p=new int[size];
    for(int i=0;i<size;i++)
    {
        p[i]=r[i];
    }
    return *this;
}
people::people(const people&r)
{
    size=r.GetSize();
    p=new int(size);
    for (int i=0;i<size;i++)
    {
        p[i]=r[i];
    }
}

int&people::operator[](int off)
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}

const int&people::operator [](int off)const
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
ostream &operator<<(ostream&out,const people&the)
{
    for (int i=0;i<the.GetSize();i++)
    {
        out<<"["<<i<<"]"<<the[i]<<endl;
    }
    return out;
}
int main()
{
    people one(20);
    try
    {
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (people::wrong)//嵌套 要加域作用符号
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    cout<<"程序结束\b\n";
    return 0;
}
```



### 多条catch

```c++
#include <iostream>
using namespace std;
const int num=5;
class people
{
public:
    people(int size=num);
    ~people(){delete[]p;}
    int&operator[](int off);
    const int&operator[](int off)const;
    int GetSize()const{return size;}
    //好几个类
    class wrong{};
    class Zero{};
    class Small{};
    class Big{};
    class Nav{};
private:
    int *p;
    int size;
};
people::people(int Size):size(Size)
{
    cout<<"调用构造函数\n";
    if (Size==0)
    {
        throw Zero();
    }
    if (Size<10)
    {
        throw Small();
    }
    if (Size>10000)
    {
        throw Big();
    }
    if (Size<1)
    {
        throw Nav();
    }
    p=new int[size];
    for (int i=0;i<size;i++)
    {
        p[i]=0;
    }
}
int&people::operator[](int off)
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
const int&people::operator[](int off)const
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
int main()
{
    try
    {
        people one(60000);
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (people::wrong)//多个catch
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    catch (people::Big)
    {
        cout<<"下标值太大\n";
    }
    catch (people::Small)
    {
        cout<<"下标值太小\n";
    }
    catch (people::Zero)
    {
        cout<<"下标值为0\n";
    }
    catch (people::Nav)
    {
        cout<<"下标值为负数\n";
    }
    cout<<"程序结束\b\n";
    return 0;
}

```



### 异常的派生

```c++
#include <iostream>
using namespace std;
const int num=5;
class people
{
public:
    people(int size=num);
    ~people(){delete[]p;}
    int&operator[](int off);
    const int&operator[](int off)const;
    int GetSize()const{return size;}
    class wrong{};
    class offset{};
    class Big:public offset{};//派生
    class Nav:public offset{};
    class Small{};
    class Zero:public Small{};
private:
    int *p;
    int size;
};
people::people(int Size):size(Size)
{
    cout<<"调用构造函数\n";
    if (Size==0)
    {
        throw Zero();
    }
    if (Size<10)
    {
        throw Small();
    }
    if (Size>10000)
    {
        throw Big();
    }
    if (Size<1)
    {
        throw Nav();
    }
    p=new int[size];
    for (int i=0;i<size;i++)
    {
        p[i]=0;
    }
}
int&people::operator[](int off)
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
const int&people::operator[](int off)const
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
int main()
{
    try
    {
        people one(60000);
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (people::wrong)
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    catch (people::offset) 
    {
        cout<<"下标值过大或为负数\n";
    }
    catch (people::Big)
    {
    /*
     big 派生自offset
     前面已经捕获了offset  
     其实代码不会运行这里了
     也就是捕获了offset后 抛出的big已经没了
    */
        cout<<"下标值太大\n";
    }
    catch (people::Small)
    {
        cout<<"下标值太小\n";
    }
    catch (people::Zero)
    {
        cout<<"下标值为0\n";
    }
    catch (people::Nav)
    {
        cout<<"下标值为负数\n";
    }
    cout<<"程序结束\b\n";
    return 0;
}

```



### 异常的成员函数

```c++
#include <iostream>
using namespace std;
const int num=5;
class people
{
public:
    people(int size=num);
    ~people(){delete[]p;}
    int&operator[](int off);
    const int&operator[](int off)const;
    int GetSize()const{return size;}
    class wrong{};
    class offset
    {
	public:
        offset(int Size):size(Size){}
        ~offset(){}
        int Get(){return size;}
	private:
        int size;
    };
    
    class Big:public offset
    {
	public:
        Big(int Size):offset(Size){}
    };
    
    class Nav:public offset
    {
	public:
        Nav(int Size):offset(Size){}
    };
    
    class Small
    {
	public:
        Small(int Size):size(Size){}
        ~Small(){}
        int get(){return size;}
	private:
        int size;
    };
    
    class Zero:public Small
    {
	public:
        Zero(int Size):Small(Size){}
    };
    
private:
    int *p;
    int size;
};
people::people(int Size):size(Size)
{
    cout<<"调用构造函数\n";
    if (Size==0)
    {
        throw Zero(Size);
    }
    if (Size<10)
    {
        throw Small(Size);
    }
    if (Size>10000)
    {
        throw Big(Size);
    }
    if (Size<1)
    {
        throw Nav(Size);
    }
    p=new int[size];
    for (int i=0;i<size;i++)
    {
        p[i]=0;
    }
}

int&people::operator[](int off)
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}

const int&people::operator[](int off)const
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
int main()
{
    try
    {
        people one(9);
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (people::Zero zero)
    {
        cout<<"下标值为0\n";
    }
    catch (people::Nav nav)
    {
        cout<<"下标值为负数\n";
    }
    catch (people::Big big)
    {
        cout<<"下标值太大\n";
    }
    catch (people::Small small)
    {
        cout<<"下标值太小\n";
        cout<<"下标值为："<<small.get()<<endl;
    }
    catch (people::offset) 
    {
        cout<<"下标值过大或为负数\n";
    }
    catch (people::wrong)
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    cout<<"程序结束\b\n";
    return 0;
}

```



### 异常类的虚函数

```c++
#include <iostream>
using namespace std;
const int num=5;
class people
{
public:
    people(int size=num);
    ~people(){delete[]p;}
    int&operator[](int off);
    const int&operator[](int off)const;
    int GetSize()const{return size;}
    
    class wrong{};
    class offset
    {
	public:
        offset(int Size):size(Size){}
        ~offset(){}
        virtual int Get(){return size;}//虚函数
        virtual void show()
        {
            cout<<"抛出offset异常\n";
            cout<<"下标值"<<size<<"出错"<<endl;
        }
	protected:
        int size;
    };
    
    class Big:public offset
    {
	public:
        Big(int Size):offset(Size){}
        virtual void show()
        {
            cout<<"抛出Big异常\n";
            cout<<"下标值"<<offset::size<<"出错"<<endl;
        }
    };
    
    class Nav:public offset
    {
	public:
        Nav(int Size):offset(Size){}
        virtual void show()
        {
            cout<<"抛出Nav异常\n";
            cout<<"下标值"<<offset::size<<"出错"<<endl;
        }
    };
    class Small
    {
	public:
        Small(int Size):size(Size){}
        ~Small(){}
        virtual int get(){return size;}
        virtual void show()
        {
            cout<<"抛出Small异常\n";
            cout<<"下标值"<<size<<"出错"<<endl;
        }
	protected:
        int size;
    };
    class Zero:public Small
    {
	public:
        Zero(int Size):Small(Size){}
        virtual void show()
        {
            cout<<"抛出Zero异常\n";
            cout<<"下标值"<<Small::size<<"出错"<<endl;
        }
    };
    private:
    int *p;
    int size;
};
people::people(int Size):size(Size)
{
    cout<<"调用构造函数\n";
    if (Size==0)
    {
        throw Zero(Size);
    }
    if (Size<10)
    {
        throw Small(Size);
    }
    if (Size>10000)
    {
        throw Big(Size);
    }
    if (Size<1)
    {
        throw Nav(Size);
    }
    p=new int[size];
    for (int i=0;i<size;i++)
    {
        p[i]=0;
    }
}
int&people::operator[](int off)
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
const int&people::operator[](int off)const
{
    if (off>=0&&off<GetSize())
    {
        return p[off];
    }
    throw wrong();
    return p[0];
}
int main()
{
    try
    {
        people one(0);
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (people::wrong)
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    catch (people::Small &small)//改成引用
    {
        small.show();
    }
    catch (people::offset &off) 
    {
        off.show();
    }
    catch (...) //捕获其他前面未捕获的
    {
        cout<<"程序出现异常"<<endl;
    }
    return 0;
}

```



### 结合点模板

```c++
#include <iostream>
using namespace std;
const int num=5;
class wrong{};
template <class T>
    class people
    {
	public:
        people(int size=num);
        ~people(){delete[]p;}
        T&operator[](int off);
        const T&operator[](int off)const;
        int GetSize()const{return size;}

        class offset
        {
		public:
            offset(int Size):size(Size){}
            ~offset(){}
            virtual int Get(){return size;}
            virtual void show()
            {
                cout<<"抛出offset异常\n";
                cout<<"下标值"<<size<<"出错"<<endl;
            }
		protected:
            int size;
        };
        
        class Big:public offset
        {
		public:
            Big(int Size):offset(Size){}
            virtual void show()
            {
                cout<<"抛出Big异常\n";
                cout<<"下标值"<<offset::size<<"出错"<<endl;
            }
        };
        
        class Nav:public offset
        {
		public:
            Nav(int Size):offset(Size){}
            virtual void show()
            {
                cout<<"抛出Nav异常\n";
                cout<<"下标值"<<offset::size<<"出错"<<endl;
            }
        };
        
        class Small
        {
		public:
            Small(int Size):size(Size){}
            ~Small(){}
            virtual int get(){return size;}
            virtual void show()
            {
                cout<<"抛出Small异常\n";
                cout<<"下标值"<<size<<"出错"<<endl;
            }
		protected:
            int size;
        };
        
        class Zero:public Small
        {
		public:
            Zero(int Size):Small(Size){}
            virtual void show()
            {
                cout<<"抛出Zero异常\n";
                cout<<"下标值"<<Small::size<<"出错"<<endl;
            }
        };
        
	private:
        int *p;
        int size;
    };

template<class T>
    people<T>::people(int Size):size(Size)
    {
        cout<<"调用构造函数\n";
        if (Size==0)
        {
            throw Zero(Size);
        }
        if (Size<10)
        {
            throw Small(Size);
        }
        if (Size>10000)
        {
            throw Big(Size);
        }
        if (Size<1)
        {
            throw Nav(Size);
        }
        p=new T[size];
        for (int i=0;i<size;i++)
        {
            p[i]=0;
        }
    }

template<class T>
    T&people<T>::operator[](int off)
    {
        if (off>=0&&off<GetSize())
        {
            return p[off];
        }
        throw wrong();
        return p[0];
    }

template<class T>
    const T&people<T>::operator[](int off)const
    {
        if (off>=0&&off<GetSize())
        {
            return p[off];
        }
        throw wrong();
        return p[0];
    }

int main()
{
    try
    {
        people<int> one(0);
        for (int i=0;i<100;i++)
        {
            one[i]=i;
            cout<<"one["<<i<<"]赋值完毕..."<<endl;
        }
    }
    catch (wrong)
    {
        cout<<"超过数组长度，不能继续执行赋值操作！\n";
    }
    catch (people<int>::Small &small)
    {
        small.show();
    }
    catch (people<int>::offset &off) 
    {
        off.show();
    }
    catch (...) 
    {
        cout<<"程序出现异常"<<endl;
    }
    return 0;
}

```

